---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: '8'

params:
  MAVEN_OPTS:
  MAVEN_CONFIG:

inputs:
  - name: pcfdemo

outputs:
  - name: build

run:
  path: pcfdemo/ci/tasks/build.sh
  args: [
    --input-dir, pcfdemo,
    --output-dir, build,
    --artifactId, pcf-demo,
    --packaging, war
  ]
